/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as PaymentCallbackRouteImport } from "./routes/payment-callback"
import { Route as GoogleCalendarCallbackRouteImport } from "./routes/google-calendar-callback"
import { Route as CustomTokenAuthRouteImport } from "./routes/custom-token-auth"
import { Route as CelloRouteImport } from "./routes/cello"
import { Route as LocalRedirectRouteRouteImport } from "./routes/local-redirect.route"
import { Route as ProtectedRouteRouteImport } from "./routes/_protected/route"
import { Route as ProtectedIndexRouteImport } from "./routes/_protected/index"
import { Route as ProtectedMiniAppSplatRouteImport } from "./routes/_protected/mini-app.$"
import { Route as ProtectedWWorkspaceIdRouteRouteImport } from "./routes/_protected/w.$workspaceId/route"
import { Route as ProtectedWWorkspaceIdIndexRouteImport } from "./routes/_protected/w.$workspaceId/index"
import { Route as ProtectedWWorkspaceIdTelegramRouteImport } from "./routes/_protected/w.$workspaceId/telegram"
import { Route as ProtectedAcceptInviteWorkspaceIdInviteCodeRouteImport } from "./routes/_protected/accept-invite.$workspaceId.$inviteCode"
import { Route as ProtectedWWorkspaceIdSettingsIndexRouteImport } from "./routes/_protected/w.$workspaceId/settings/index"
import { Route as ProtectedWWorkspaceIdOutreachIndexRouteImport } from "./routes/_protected/w.$workspaceId/outreach/index"
import { Route as ProtectedWWorkspaceIdOnboardingIndexRouteImport } from "./routes/_protected/w.$workspaceId/onboarding/index"
import { Route as ProtectedWWorkspaceIdContactsIndexRouteImport } from "./routes/_protected/w.$workspaceId/contacts/index"
import { Route as ProtectedWWorkspaceIdWalletTopUpRouteImport } from "./routes/_protected/w.$workspaceId/wallet/top-up"
import { Route as ProtectedWWorkspaceIdToolsPhoneNumbersConverterRouteImport } from "./routes/_protected/w.$workspaceId/tools/phone-numbers-converter"
import { Route as ProtectedWWorkspaceIdToolsLookalikeAudienceRouteImport } from "./routes/_protected/w.$workspaceId/tools/lookalike-audience"
import { Route as ProtectedWWorkspaceIdToolsGroupParserRouteImport } from "./routes/_protected/w.$workspaceId/tools/group-parser"
import { Route as ProtectedWWorkspaceIdSettingsTelegramSyncRouteImport } from "./routes/_protected/w.$workspaceId/settings/telegram-sync"
import { Route as ProtectedWWorkspaceIdSettingsSubscriptionRouteImport } from "./routes/_protected/w.$workspaceId/settings/subscription"
import { Route as ProtectedWWorkspaceIdSettingsNotificationsRouteImport } from "./routes/_protected/w.$workspaceId/settings/notifications"
import { Route as ProtectedWWorkspaceIdSettingsLocaleRouteImport } from "./routes/_protected/w.$workspaceId/settings/locale"
import { Route as ProtectedWWorkspaceIdSettingsHelpRouteImport } from "./routes/_protected/w.$workspaceId/settings/help"
import { Route as ProtectedWWorkspaceIdSettingsGoogleCalendarRouteImport } from "./routes/_protected/w.$workspaceId/settings/google-calendar"
import { Route as ProtectedWWorkspaceIdSettingsFeatureFlagsRouteImport } from "./routes/_protected/w.$workspaceId/settings/feature-flags"
import { Route as ProtectedWWorkspaceIdSettingsExportRouteImport } from "./routes/_protected/w.$workspaceId/settings/export"
import { Route as ProtectedWWorkspaceIdSettingsConnectCrmRouteImport } from "./routes/_protected/w.$workspaceId/settings/connect-crm"
import { Route as ProtectedWWorkspaceIdSettingsAffiliateRouteImport } from "./routes/_protected/w.$workspaceId/settings/affiliate"
import { Route as ProtectedWWorkspaceIdOutreachScheduleRouteImport } from "./routes/_protected/w.$workspaceId/outreach/schedule"
import { Route as ProtectedWWorkspaceIdOutreachAiBotRouteImport } from "./routes/_protected/w.$workspaceId/outreach/ai-bot"
import { Route as ProtectedWWorkspaceIdOnboardingStepIdRouteImport } from "./routes/_protected/w.$workspaceId/onboarding/$stepId"
import { Route as ProtectedWWorkspaceIdContactsNewRouteImport } from "./routes/_protected/w.$workspaceId/contacts/new"
import { Route as ProtectedWWorkspaceIdAddPendingActivityIdRouteImport } from "./routes/_protected/w.$workspaceId/add-pending-activity.$id"
import { Route as ProtectedWWorkspaceIdSettingsWorkspaceIndexRouteImport } from "./routes/_protected/w.$workspaceId/settings/workspace/index"
import { Route as ProtectedWWorkspaceIdSettingsApiKeysIndexRouteImport } from "./routes/_protected/w.$workspaceId/settings/api-keys/index"
import { Route as ProtectedWWorkspaceIdOutreachTelegramAccountsIndexRouteImport } from "./routes/_protected/w.$workspaceId/outreach/telegram-accounts/index"
import { Route as ProtectedWWorkspaceIdContactsContactIdIndexRouteImport } from "./routes/_protected/w.$workspaceId/contacts/$contactId/index"
import { Route as ProtectedWWorkspaceIdSettingsWorkspaceNewRouteImport } from "./routes/_protected/w.$workspaceId/settings/workspace/new"
import { Route as ProtectedWWorkspaceIdSettingsWorkspaceInviteRouteImport } from "./routes/_protected/w.$workspaceId/settings/workspace/invite"
import { Route as ProtectedWWorkspaceIdSettingsOrganizationOrganizationIdRouteImport } from "./routes/_protected/w.$workspaceId/settings/organization/$organizationId"
import { Route as ProtectedWWorkspaceIdSettingsApiKeysKeyIdRouteImport } from "./routes/_protected/w.$workspaceId/settings/api-keys/$keyId"
import { Route as ProtectedWWorkspaceIdOutreachTelegramAccountsNewRouteImport } from "./routes/_protected/w.$workspaceId/outreach/telegram-accounts/new"
import { Route as ProtectedWWorkspaceIdOutreachTelegramAccountsBuyRouteImport } from "./routes/_protected/w.$workspaceId/outreach/telegram-accounts/buy"
import { Route as ProtectedWWorkspaceIdOutreachTelegramAccountsAccountIdRouteImport } from "./routes/_protected/w.$workspaceId/outreach/telegram-accounts/$accountId"
import { Route as ProtectedWWorkspaceIdContactsContactIdEditRouteImport } from "./routes/_protected/w.$workspaceId/contacts/$contactId/edit"
import { Route as ProtectedWWorkspaceIdSettingsPropertiesObjectTypeIndexRouteImport } from "./routes/_protected/w.$workspaceId/settings/properties.$objectType/index"
import { Route as ProtectedWWorkspaceIdSettingsApiKeysWebhooksIndexRouteImport } from "./routes/_protected/w.$workspaceId/settings/api-keys/webhooks.index"
import { Route as ProtectedWWorkspaceIdOutreachSequencesNewIndexRouteImport } from "./routes/_protected/w.$workspaceId/outreach/sequences/new.index"
import { Route as ProtectedWWorkspaceIdOutreachSequencesIdIndexRouteImport } from "./routes/_protected/w.$workspaceId/outreach/sequences/$id.index"
import { Route as ProtectedWWorkspaceIdSettingsWorkspaceUserUserIdRouteImport } from "./routes/_protected/w.$workspaceId/settings/workspace/user.$userId"
import { Route as ProtectedWWorkspaceIdSettingsApiKeysWebhooksWebhookIdRouteImport } from "./routes/_protected/w.$workspaceId/settings/api-keys/webhooks.$webhookId"
import { Route as ProtectedWWorkspaceIdOutreachSequencesNewCsvRouteImport } from "./routes/_protected/w.$workspaceId/outreach/sequences/new.csv"
import { Route as ProtectedWWorkspaceIdOutreachSequencesNewCrmRouteImport } from "./routes/_protected/w.$workspaceId/outreach/sequences/new.crm"
import { Route as ProtectedWWorkspaceIdOutreachSequencesIdLeadsRouteImport } from "./routes/_protected/w.$workspaceId/outreach/sequences/$id.leads"
import { Route as ProtectedWWorkspaceIdOutreachSequencesIdAccountsRouteImport } from "./routes/_protected/w.$workspaceId/outreach/sequences/$id.accounts"
import { Route as ProtectedWWorkspaceIdContactsContactIdActivitiesNewRouteImport } from "./routes/_protected/w.$workspaceId/contacts/$contactId/activities/new"
import { Route as ProtectedWWorkspaceIdOutreachSequencesIdContactSettingsIndexRouteImport } from "./routes/_protected/w.$workspaceId/outreach/sequences/$id.contact-settings.index"
import { Route as ProtectedWWorkspaceIdSettingsWorkspaceAcceptInviteWIdInviteCodeRouteImport } from "./routes/_protected/w.$workspaceId/settings/workspace/accept-invite.$wId.$inviteCode"
import { Route as ProtectedWWorkspaceIdSettingsPropertiesObjectTypeNewTypeRouteImport } from "./routes/_protected/w.$workspaceId/settings/properties.$objectType/new.$type"
import { Route as ProtectedWWorkspaceIdSettingsPropertiesObjectTypeKeyEditRouteImport } from "./routes/_protected/w.$workspaceId/settings/properties.$objectType/$key.edit"
import { Route as ProtectedWWorkspaceIdSettingsMembersAcceptInviteWIdInviteCodeRouteImport } from "./routes/_protected/w.$workspaceId/settings/members.accept-invite.$wId.$inviteCode"
import { Route as ProtectedWWorkspaceIdOutreachSequencesIdContactSettingsOwnersRouteImport } from "./routes/_protected/w.$workspaceId/outreach/sequences/$id.contact-settings.owners"
import { Route as ProtectedWWorkspaceIdContactsContactIdActivitiesActivityIdEditRouteImport } from "./routes/_protected/w.$workspaceId/contacts/$contactId/activities/$activityId.edit"

const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: "/payment-callback",
  path: "/payment-callback",
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleCalendarCallbackRoute = GoogleCalendarCallbackRouteImport.update({
  id: "/google-calendar-callback",
  path: "/google-calendar-callback",
  getParentRoute: () => rootRouteImport,
} as any)
const CustomTokenAuthRoute = CustomTokenAuthRouteImport.update({
  id: "/custom-token-auth",
  path: "/custom-token-auth",
  getParentRoute: () => rootRouteImport,
} as any)
const CelloRoute = CelloRouteImport.update({
  id: "/cello",
  path: "/cello",
  getParentRoute: () => rootRouteImport,
} as any)
const LocalRedirectRouteRoute = LocalRedirectRouteRouteImport.update({
  id: "/local-redirect",
  path: "/local-redirect",
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: "/_protected",
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedMiniAppSplatRoute = ProtectedMiniAppSplatRouteImport.update({
  id: "/mini-app/$",
  path: "/mini-app/$",
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedWWorkspaceIdRouteRoute =
  ProtectedWWorkspaceIdRouteRouteImport.update({
    id: "/w/$workspaceId",
    path: "/w/$workspaceId",
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedWWorkspaceIdIndexRoute =
  ProtectedWWorkspaceIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdTelegramRoute =
  ProtectedWWorkspaceIdTelegramRouteImport.update({
    id: "/telegram",
    path: "/telegram",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedAcceptInviteWorkspaceIdInviteCodeRoute =
  ProtectedAcceptInviteWorkspaceIdInviteCodeRouteImport.update({
    id: "/accept-invite/$workspaceId/$inviteCode",
    path: "/accept-invite/$workspaceId/$inviteCode",
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedWWorkspaceIdSettingsIndexRoute =
  ProtectedWWorkspaceIdSettingsIndexRouteImport.update({
    id: "/settings/",
    path: "/settings/",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdOutreachIndexRoute =
  ProtectedWWorkspaceIdOutreachIndexRouteImport.update({
    id: "/outreach/",
    path: "/outreach/",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdOnboardingIndexRoute =
  ProtectedWWorkspaceIdOnboardingIndexRouteImport.update({
    id: "/onboarding/",
    path: "/onboarding/",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdContactsIndexRoute =
  ProtectedWWorkspaceIdContactsIndexRouteImport.update({
    id: "/contacts/",
    path: "/contacts/",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdWalletTopUpRoute =
  ProtectedWWorkspaceIdWalletTopUpRouteImport.update({
    id: "/wallet/top-up",
    path: "/wallet/top-up",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdToolsPhoneNumbersConverterRoute =
  ProtectedWWorkspaceIdToolsPhoneNumbersConverterRouteImport.update({
    id: "/tools/phone-numbers-converter",
    path: "/tools/phone-numbers-converter",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdToolsLookalikeAudienceRoute =
  ProtectedWWorkspaceIdToolsLookalikeAudienceRouteImport.update({
    id: "/tools/lookalike-audience",
    path: "/tools/lookalike-audience",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdToolsGroupParserRoute =
  ProtectedWWorkspaceIdToolsGroupParserRouteImport.update({
    id: "/tools/group-parser",
    path: "/tools/group-parser",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdSettingsTelegramSyncRoute =
  ProtectedWWorkspaceIdSettingsTelegramSyncRouteImport.update({
    id: "/settings/telegram-sync",
    path: "/settings/telegram-sync",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdSettingsSubscriptionRoute =
  ProtectedWWorkspaceIdSettingsSubscriptionRouteImport.update({
    id: "/settings/subscription",
    path: "/settings/subscription",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdSettingsNotificationsRoute =
  ProtectedWWorkspaceIdSettingsNotificationsRouteImport.update({
    id: "/settings/notifications",
    path: "/settings/notifications",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdSettingsLocaleRoute =
  ProtectedWWorkspaceIdSettingsLocaleRouteImport.update({
    id: "/settings/locale",
    path: "/settings/locale",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdSettingsHelpRoute =
  ProtectedWWorkspaceIdSettingsHelpRouteImport.update({
    id: "/settings/help",
    path: "/settings/help",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdSettingsGoogleCalendarRoute =
  ProtectedWWorkspaceIdSettingsGoogleCalendarRouteImport.update({
    id: "/settings/google-calendar",
    path: "/settings/google-calendar",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdSettingsFeatureFlagsRoute =
  ProtectedWWorkspaceIdSettingsFeatureFlagsRouteImport.update({
    id: "/settings/feature-flags",
    path: "/settings/feature-flags",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdSettingsExportRoute =
  ProtectedWWorkspaceIdSettingsExportRouteImport.update({
    id: "/settings/export",
    path: "/settings/export",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdSettingsConnectCrmRoute =
  ProtectedWWorkspaceIdSettingsConnectCrmRouteImport.update({
    id: "/settings/connect-crm",
    path: "/settings/connect-crm",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdSettingsAffiliateRoute =
  ProtectedWWorkspaceIdSettingsAffiliateRouteImport.update({
    id: "/settings/affiliate",
    path: "/settings/affiliate",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdOutreachScheduleRoute =
  ProtectedWWorkspaceIdOutreachScheduleRouteImport.update({
    id: "/outreach/schedule",
    path: "/outreach/schedule",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdOutreachAiBotRoute =
  ProtectedWWorkspaceIdOutreachAiBotRouteImport.update({
    id: "/outreach/ai-bot",
    path: "/outreach/ai-bot",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdOnboardingStepIdRoute =
  ProtectedWWorkspaceIdOnboardingStepIdRouteImport.update({
    id: "/onboarding/$stepId",
    path: "/onboarding/$stepId",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdContactsNewRoute =
  ProtectedWWorkspaceIdContactsNewRouteImport.update({
    id: "/contacts/new",
    path: "/contacts/new",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdAddPendingActivityIdRoute =
  ProtectedWWorkspaceIdAddPendingActivityIdRouteImport.update({
    id: "/add-pending-activity/$id",
    path: "/add-pending-activity/$id",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdSettingsWorkspaceIndexRoute =
  ProtectedWWorkspaceIdSettingsWorkspaceIndexRouteImport.update({
    id: "/settings/workspace/",
    path: "/settings/workspace/",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdSettingsApiKeysIndexRoute =
  ProtectedWWorkspaceIdSettingsApiKeysIndexRouteImport.update({
    id: "/settings/api-keys/",
    path: "/settings/api-keys/",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdOutreachTelegramAccountsIndexRoute =
  ProtectedWWorkspaceIdOutreachTelegramAccountsIndexRouteImport.update({
    id: "/outreach/telegram-accounts/",
    path: "/outreach/telegram-accounts/",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdContactsContactIdIndexRoute =
  ProtectedWWorkspaceIdContactsContactIdIndexRouteImport.update({
    id: "/contacts/$contactId/",
    path: "/contacts/$contactId/",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdSettingsWorkspaceNewRoute =
  ProtectedWWorkspaceIdSettingsWorkspaceNewRouteImport.update({
    id: "/settings/workspace/new",
    path: "/settings/workspace/new",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdSettingsWorkspaceInviteRoute =
  ProtectedWWorkspaceIdSettingsWorkspaceInviteRouteImport.update({
    id: "/settings/workspace/invite",
    path: "/settings/workspace/invite",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdSettingsOrganizationOrganizationIdRoute =
  ProtectedWWorkspaceIdSettingsOrganizationOrganizationIdRouteImport.update({
    id: "/settings/organization/$organizationId",
    path: "/settings/organization/$organizationId",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdSettingsApiKeysKeyIdRoute =
  ProtectedWWorkspaceIdSettingsApiKeysKeyIdRouteImport.update({
    id: "/settings/api-keys/$keyId",
    path: "/settings/api-keys/$keyId",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdOutreachTelegramAccountsNewRoute =
  ProtectedWWorkspaceIdOutreachTelegramAccountsNewRouteImport.update({
    id: "/outreach/telegram-accounts/new",
    path: "/outreach/telegram-accounts/new",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdOutreachTelegramAccountsBuyRoute =
  ProtectedWWorkspaceIdOutreachTelegramAccountsBuyRouteImport.update({
    id: "/outreach/telegram-accounts/buy",
    path: "/outreach/telegram-accounts/buy",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdOutreachTelegramAccountsAccountIdRoute =
  ProtectedWWorkspaceIdOutreachTelegramAccountsAccountIdRouteImport.update({
    id: "/outreach/telegram-accounts/$accountId",
    path: "/outreach/telegram-accounts/$accountId",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdContactsContactIdEditRoute =
  ProtectedWWorkspaceIdContactsContactIdEditRouteImport.update({
    id: "/contacts/$contactId/edit",
    path: "/contacts/$contactId/edit",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdSettingsPropertiesObjectTypeIndexRoute =
  ProtectedWWorkspaceIdSettingsPropertiesObjectTypeIndexRouteImport.update({
    id: "/settings/properties/$objectType/",
    path: "/settings/properties/$objectType/",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdSettingsApiKeysWebhooksIndexRoute =
  ProtectedWWorkspaceIdSettingsApiKeysWebhooksIndexRouteImport.update({
    id: "/settings/api-keys/webhooks/",
    path: "/settings/api-keys/webhooks/",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdOutreachSequencesNewIndexRoute =
  ProtectedWWorkspaceIdOutreachSequencesNewIndexRouteImport.update({
    id: "/outreach/sequences/new/",
    path: "/outreach/sequences/new/",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdOutreachSequencesIdIndexRoute =
  ProtectedWWorkspaceIdOutreachSequencesIdIndexRouteImport.update({
    id: "/outreach/sequences/$id/",
    path: "/outreach/sequences/$id/",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdSettingsWorkspaceUserUserIdRoute =
  ProtectedWWorkspaceIdSettingsWorkspaceUserUserIdRouteImport.update({
    id: "/settings/workspace/user/$userId",
    path: "/settings/workspace/user/$userId",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdSettingsApiKeysWebhooksWebhookIdRoute =
  ProtectedWWorkspaceIdSettingsApiKeysWebhooksWebhookIdRouteImport.update({
    id: "/settings/api-keys/webhooks/$webhookId",
    path: "/settings/api-keys/webhooks/$webhookId",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdOutreachSequencesNewCsvRoute =
  ProtectedWWorkspaceIdOutreachSequencesNewCsvRouteImport.update({
    id: "/outreach/sequences/new/csv",
    path: "/outreach/sequences/new/csv",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdOutreachSequencesNewCrmRoute =
  ProtectedWWorkspaceIdOutreachSequencesNewCrmRouteImport.update({
    id: "/outreach/sequences/new/crm",
    path: "/outreach/sequences/new/crm",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdOutreachSequencesIdLeadsRoute =
  ProtectedWWorkspaceIdOutreachSequencesIdLeadsRouteImport.update({
    id: "/outreach/sequences/$id/leads",
    path: "/outreach/sequences/$id/leads",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdOutreachSequencesIdAccountsRoute =
  ProtectedWWorkspaceIdOutreachSequencesIdAccountsRouteImport.update({
    id: "/outreach/sequences/$id/accounts",
    path: "/outreach/sequences/$id/accounts",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdContactsContactIdActivitiesNewRoute =
  ProtectedWWorkspaceIdContactsContactIdActivitiesNewRouteImport.update({
    id: "/contacts/$contactId/activities/new",
    path: "/contacts/$contactId/activities/new",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdOutreachSequencesIdContactSettingsIndexRoute =
  ProtectedWWorkspaceIdOutreachSequencesIdContactSettingsIndexRouteImport.update(
    {
      id: "/outreach/sequences/$id/contact-settings/",
      path: "/outreach/sequences/$id/contact-settings/",
      getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
    } as any,
  )
const ProtectedWWorkspaceIdSettingsWorkspaceAcceptInviteWIdInviteCodeRoute =
  ProtectedWWorkspaceIdSettingsWorkspaceAcceptInviteWIdInviteCodeRouteImport.update(
    {
      id: "/settings/workspace/accept-invite/$wId/$inviteCode",
      path: "/settings/workspace/accept-invite/$wId/$inviteCode",
      getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
    } as any,
  )
const ProtectedWWorkspaceIdSettingsPropertiesObjectTypeNewTypeRoute =
  ProtectedWWorkspaceIdSettingsPropertiesObjectTypeNewTypeRouteImport.update({
    id: "/settings/properties/$objectType/new/$type",
    path: "/settings/properties/$objectType/new/$type",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdSettingsPropertiesObjectTypeKeyEditRoute =
  ProtectedWWorkspaceIdSettingsPropertiesObjectTypeKeyEditRouteImport.update({
    id: "/settings/properties/$objectType/$key/edit",
    path: "/settings/properties/$objectType/$key/edit",
    getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
  } as any)
const ProtectedWWorkspaceIdSettingsMembersAcceptInviteWIdInviteCodeRoute =
  ProtectedWWorkspaceIdSettingsMembersAcceptInviteWIdInviteCodeRouteImport.update(
    {
      id: "/settings/members/accept-invite/$wId/$inviteCode",
      path: "/settings/members/accept-invite/$wId/$inviteCode",
      getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
    } as any,
  )
const ProtectedWWorkspaceIdOutreachSequencesIdContactSettingsOwnersRoute =
  ProtectedWWorkspaceIdOutreachSequencesIdContactSettingsOwnersRouteImport.update(
    {
      id: "/outreach/sequences/$id/contact-settings/owners",
      path: "/outreach/sequences/$id/contact-settings/owners",
      getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
    } as any,
  )
const ProtectedWWorkspaceIdContactsContactIdActivitiesActivityIdEditRoute =
  ProtectedWWorkspaceIdContactsContactIdActivitiesActivityIdEditRouteImport.update(
    {
      id: "/contacts/$contactId/activities/$activityId/edit",
      path: "/contacts/$contactId/activities/$activityId/edit",
      getParentRoute: () => ProtectedWWorkspaceIdRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  "/": typeof ProtectedIndexRoute
  "/local-redirect": typeof LocalRedirectRouteRoute
  "/cello": typeof CelloRoute
  "/custom-token-auth": typeof CustomTokenAuthRoute
  "/google-calendar-callback": typeof GoogleCalendarCallbackRoute
  "/payment-callback": typeof PaymentCallbackRoute
  "/w/$workspaceId": typeof ProtectedWWorkspaceIdRouteRouteWithChildren
  "/mini-app/$": typeof ProtectedMiniAppSplatRoute
  "/accept-invite/$workspaceId/$inviteCode": typeof ProtectedAcceptInviteWorkspaceIdInviteCodeRoute
  "/w/$workspaceId/telegram": typeof ProtectedWWorkspaceIdTelegramRoute
  "/w/$workspaceId/": typeof ProtectedWWorkspaceIdIndexRoute
  "/w/$workspaceId/add-pending-activity/$id": typeof ProtectedWWorkspaceIdAddPendingActivityIdRoute
  "/w/$workspaceId/contacts/new": typeof ProtectedWWorkspaceIdContactsNewRoute
  "/w/$workspaceId/onboarding/$stepId": typeof ProtectedWWorkspaceIdOnboardingStepIdRoute
  "/w/$workspaceId/outreach/ai-bot": typeof ProtectedWWorkspaceIdOutreachAiBotRoute
  "/w/$workspaceId/outreach/schedule": typeof ProtectedWWorkspaceIdOutreachScheduleRoute
  "/w/$workspaceId/settings/affiliate": typeof ProtectedWWorkspaceIdSettingsAffiliateRoute
  "/w/$workspaceId/settings/connect-crm": typeof ProtectedWWorkspaceIdSettingsConnectCrmRoute
  "/w/$workspaceId/settings/export": typeof ProtectedWWorkspaceIdSettingsExportRoute
  "/w/$workspaceId/settings/feature-flags": typeof ProtectedWWorkspaceIdSettingsFeatureFlagsRoute
  "/w/$workspaceId/settings/google-calendar": typeof ProtectedWWorkspaceIdSettingsGoogleCalendarRoute
  "/w/$workspaceId/settings/help": typeof ProtectedWWorkspaceIdSettingsHelpRoute
  "/w/$workspaceId/settings/locale": typeof ProtectedWWorkspaceIdSettingsLocaleRoute
  "/w/$workspaceId/settings/notifications": typeof ProtectedWWorkspaceIdSettingsNotificationsRoute
  "/w/$workspaceId/settings/subscription": typeof ProtectedWWorkspaceIdSettingsSubscriptionRoute
  "/w/$workspaceId/settings/telegram-sync": typeof ProtectedWWorkspaceIdSettingsTelegramSyncRoute
  "/w/$workspaceId/tools/group-parser": typeof ProtectedWWorkspaceIdToolsGroupParserRoute
  "/w/$workspaceId/tools/lookalike-audience": typeof ProtectedWWorkspaceIdToolsLookalikeAudienceRoute
  "/w/$workspaceId/tools/phone-numbers-converter": typeof ProtectedWWorkspaceIdToolsPhoneNumbersConverterRoute
  "/w/$workspaceId/wallet/top-up": typeof ProtectedWWorkspaceIdWalletTopUpRoute
  "/w/$workspaceId/contacts/": typeof ProtectedWWorkspaceIdContactsIndexRoute
  "/w/$workspaceId/onboarding/": typeof ProtectedWWorkspaceIdOnboardingIndexRoute
  "/w/$workspaceId/outreach/": typeof ProtectedWWorkspaceIdOutreachIndexRoute
  "/w/$workspaceId/settings/": typeof ProtectedWWorkspaceIdSettingsIndexRoute
  "/w/$workspaceId/contacts/$contactId/edit": typeof ProtectedWWorkspaceIdContactsContactIdEditRoute
  "/w/$workspaceId/outreach/telegram-accounts/$accountId": typeof ProtectedWWorkspaceIdOutreachTelegramAccountsAccountIdRoute
  "/w/$workspaceId/outreach/telegram-accounts/buy": typeof ProtectedWWorkspaceIdOutreachTelegramAccountsBuyRoute
  "/w/$workspaceId/outreach/telegram-accounts/new": typeof ProtectedWWorkspaceIdOutreachTelegramAccountsNewRoute
  "/w/$workspaceId/settings/api-keys/$keyId": typeof ProtectedWWorkspaceIdSettingsApiKeysKeyIdRoute
  "/w/$workspaceId/settings/organization/$organizationId": typeof ProtectedWWorkspaceIdSettingsOrganizationOrganizationIdRoute
  "/w/$workspaceId/settings/workspace/invite": typeof ProtectedWWorkspaceIdSettingsWorkspaceInviteRoute
  "/w/$workspaceId/settings/workspace/new": typeof ProtectedWWorkspaceIdSettingsWorkspaceNewRoute
  "/w/$workspaceId/contacts/$contactId/": typeof ProtectedWWorkspaceIdContactsContactIdIndexRoute
  "/w/$workspaceId/outreach/telegram-accounts/": typeof ProtectedWWorkspaceIdOutreachTelegramAccountsIndexRoute
  "/w/$workspaceId/settings/api-keys/": typeof ProtectedWWorkspaceIdSettingsApiKeysIndexRoute
  "/w/$workspaceId/settings/workspace/": typeof ProtectedWWorkspaceIdSettingsWorkspaceIndexRoute
  "/w/$workspaceId/contacts/$contactId/activities/new": typeof ProtectedWWorkspaceIdContactsContactIdActivitiesNewRoute
  "/w/$workspaceId/outreach/sequences/$id/accounts": typeof ProtectedWWorkspaceIdOutreachSequencesIdAccountsRoute
  "/w/$workspaceId/outreach/sequences/$id/leads": typeof ProtectedWWorkspaceIdOutreachSequencesIdLeadsRoute
  "/w/$workspaceId/outreach/sequences/new/crm": typeof ProtectedWWorkspaceIdOutreachSequencesNewCrmRoute
  "/w/$workspaceId/outreach/sequences/new/csv": typeof ProtectedWWorkspaceIdOutreachSequencesNewCsvRoute
  "/w/$workspaceId/settings/api-keys/webhooks/$webhookId": typeof ProtectedWWorkspaceIdSettingsApiKeysWebhooksWebhookIdRoute
  "/w/$workspaceId/settings/workspace/user/$userId": typeof ProtectedWWorkspaceIdSettingsWorkspaceUserUserIdRoute
  "/w/$workspaceId/outreach/sequences/$id/": typeof ProtectedWWorkspaceIdOutreachSequencesIdIndexRoute
  "/w/$workspaceId/outreach/sequences/new/": typeof ProtectedWWorkspaceIdOutreachSequencesNewIndexRoute
  "/w/$workspaceId/settings/api-keys/webhooks/": typeof ProtectedWWorkspaceIdSettingsApiKeysWebhooksIndexRoute
  "/w/$workspaceId/settings/properties/$objectType/": typeof ProtectedWWorkspaceIdSettingsPropertiesObjectTypeIndexRoute
  "/w/$workspaceId/contacts/$contactId/activities/$activityId/edit": typeof ProtectedWWorkspaceIdContactsContactIdActivitiesActivityIdEditRoute
  "/w/$workspaceId/outreach/sequences/$id/contact-settings/owners": typeof ProtectedWWorkspaceIdOutreachSequencesIdContactSettingsOwnersRoute
  "/w/$workspaceId/settings/members/accept-invite/$wId/$inviteCode": typeof ProtectedWWorkspaceIdSettingsMembersAcceptInviteWIdInviteCodeRoute
  "/w/$workspaceId/settings/properties/$objectType/$key/edit": typeof ProtectedWWorkspaceIdSettingsPropertiesObjectTypeKeyEditRoute
  "/w/$workspaceId/settings/properties/$objectType/new/$type": typeof ProtectedWWorkspaceIdSettingsPropertiesObjectTypeNewTypeRoute
  "/w/$workspaceId/settings/workspace/accept-invite/$wId/$inviteCode": typeof ProtectedWWorkspaceIdSettingsWorkspaceAcceptInviteWIdInviteCodeRoute
  "/w/$workspaceId/outreach/sequences/$id/contact-settings/": typeof ProtectedWWorkspaceIdOutreachSequencesIdContactSettingsIndexRoute
}
export interface FileRoutesByTo {
  "/local-redirect": typeof LocalRedirectRouteRoute
  "/cello": typeof CelloRoute
  "/custom-token-auth": typeof CustomTokenAuthRoute
  "/google-calendar-callback": typeof GoogleCalendarCallbackRoute
  "/payment-callback": typeof PaymentCallbackRoute
  "/": typeof ProtectedIndexRoute
  "/mini-app/$": typeof ProtectedMiniAppSplatRoute
  "/accept-invite/$workspaceId/$inviteCode": typeof ProtectedAcceptInviteWorkspaceIdInviteCodeRoute
  "/w/$workspaceId/telegram": typeof ProtectedWWorkspaceIdTelegramRoute
  "/w/$workspaceId": typeof ProtectedWWorkspaceIdIndexRoute
  "/w/$workspaceId/add-pending-activity/$id": typeof ProtectedWWorkspaceIdAddPendingActivityIdRoute
  "/w/$workspaceId/contacts/new": typeof ProtectedWWorkspaceIdContactsNewRoute
  "/w/$workspaceId/onboarding/$stepId": typeof ProtectedWWorkspaceIdOnboardingStepIdRoute
  "/w/$workspaceId/outreach/ai-bot": typeof ProtectedWWorkspaceIdOutreachAiBotRoute
  "/w/$workspaceId/outreach/schedule": typeof ProtectedWWorkspaceIdOutreachScheduleRoute
  "/w/$workspaceId/settings/affiliate": typeof ProtectedWWorkspaceIdSettingsAffiliateRoute
  "/w/$workspaceId/settings/connect-crm": typeof ProtectedWWorkspaceIdSettingsConnectCrmRoute
  "/w/$workspaceId/settings/export": typeof ProtectedWWorkspaceIdSettingsExportRoute
  "/w/$workspaceId/settings/feature-flags": typeof ProtectedWWorkspaceIdSettingsFeatureFlagsRoute
  "/w/$workspaceId/settings/google-calendar": typeof ProtectedWWorkspaceIdSettingsGoogleCalendarRoute
  "/w/$workspaceId/settings/help": typeof ProtectedWWorkspaceIdSettingsHelpRoute
  "/w/$workspaceId/settings/locale": typeof ProtectedWWorkspaceIdSettingsLocaleRoute
  "/w/$workspaceId/settings/notifications": typeof ProtectedWWorkspaceIdSettingsNotificationsRoute
  "/w/$workspaceId/settings/subscription": typeof ProtectedWWorkspaceIdSettingsSubscriptionRoute
  "/w/$workspaceId/settings/telegram-sync": typeof ProtectedWWorkspaceIdSettingsTelegramSyncRoute
  "/w/$workspaceId/tools/group-parser": typeof ProtectedWWorkspaceIdToolsGroupParserRoute
  "/w/$workspaceId/tools/lookalike-audience": typeof ProtectedWWorkspaceIdToolsLookalikeAudienceRoute
  "/w/$workspaceId/tools/phone-numbers-converter": typeof ProtectedWWorkspaceIdToolsPhoneNumbersConverterRoute
  "/w/$workspaceId/wallet/top-up": typeof ProtectedWWorkspaceIdWalletTopUpRoute
  "/w/$workspaceId/contacts": typeof ProtectedWWorkspaceIdContactsIndexRoute
  "/w/$workspaceId/onboarding": typeof ProtectedWWorkspaceIdOnboardingIndexRoute
  "/w/$workspaceId/outreach": typeof ProtectedWWorkspaceIdOutreachIndexRoute
  "/w/$workspaceId/settings": typeof ProtectedWWorkspaceIdSettingsIndexRoute
  "/w/$workspaceId/contacts/$contactId/edit": typeof ProtectedWWorkspaceIdContactsContactIdEditRoute
  "/w/$workspaceId/outreach/telegram-accounts/$accountId": typeof ProtectedWWorkspaceIdOutreachTelegramAccountsAccountIdRoute
  "/w/$workspaceId/outreach/telegram-accounts/buy": typeof ProtectedWWorkspaceIdOutreachTelegramAccountsBuyRoute
  "/w/$workspaceId/outreach/telegram-accounts/new": typeof ProtectedWWorkspaceIdOutreachTelegramAccountsNewRoute
  "/w/$workspaceId/settings/api-keys/$keyId": typeof ProtectedWWorkspaceIdSettingsApiKeysKeyIdRoute
  "/w/$workspaceId/settings/organization/$organizationId": typeof ProtectedWWorkspaceIdSettingsOrganizationOrganizationIdRoute
  "/w/$workspaceId/settings/workspace/invite": typeof ProtectedWWorkspaceIdSettingsWorkspaceInviteRoute
  "/w/$workspaceId/settings/workspace/new": typeof ProtectedWWorkspaceIdSettingsWorkspaceNewRoute
  "/w/$workspaceId/contacts/$contactId": typeof ProtectedWWorkspaceIdContactsContactIdIndexRoute
  "/w/$workspaceId/outreach/telegram-accounts": typeof ProtectedWWorkspaceIdOutreachTelegramAccountsIndexRoute
  "/w/$workspaceId/settings/api-keys": typeof ProtectedWWorkspaceIdSettingsApiKeysIndexRoute
  "/w/$workspaceId/settings/workspace": typeof ProtectedWWorkspaceIdSettingsWorkspaceIndexRoute
  "/w/$workspaceId/contacts/$contactId/activities/new": typeof ProtectedWWorkspaceIdContactsContactIdActivitiesNewRoute
  "/w/$workspaceId/outreach/sequences/$id/accounts": typeof ProtectedWWorkspaceIdOutreachSequencesIdAccountsRoute
  "/w/$workspaceId/outreach/sequences/$id/leads": typeof ProtectedWWorkspaceIdOutreachSequencesIdLeadsRoute
  "/w/$workspaceId/outreach/sequences/new/crm": typeof ProtectedWWorkspaceIdOutreachSequencesNewCrmRoute
  "/w/$workspaceId/outreach/sequences/new/csv": typeof ProtectedWWorkspaceIdOutreachSequencesNewCsvRoute
  "/w/$workspaceId/settings/api-keys/webhooks/$webhookId": typeof ProtectedWWorkspaceIdSettingsApiKeysWebhooksWebhookIdRoute
  "/w/$workspaceId/settings/workspace/user/$userId": typeof ProtectedWWorkspaceIdSettingsWorkspaceUserUserIdRoute
  "/w/$workspaceId/outreach/sequences/$id": typeof ProtectedWWorkspaceIdOutreachSequencesIdIndexRoute
  "/w/$workspaceId/outreach/sequences/new": typeof ProtectedWWorkspaceIdOutreachSequencesNewIndexRoute
  "/w/$workspaceId/settings/api-keys/webhooks": typeof ProtectedWWorkspaceIdSettingsApiKeysWebhooksIndexRoute
  "/w/$workspaceId/settings/properties/$objectType": typeof ProtectedWWorkspaceIdSettingsPropertiesObjectTypeIndexRoute
  "/w/$workspaceId/contacts/$contactId/activities/$activityId/edit": typeof ProtectedWWorkspaceIdContactsContactIdActivitiesActivityIdEditRoute
  "/w/$workspaceId/outreach/sequences/$id/contact-settings/owners": typeof ProtectedWWorkspaceIdOutreachSequencesIdContactSettingsOwnersRoute
  "/w/$workspaceId/settings/members/accept-invite/$wId/$inviteCode": typeof ProtectedWWorkspaceIdSettingsMembersAcceptInviteWIdInviteCodeRoute
  "/w/$workspaceId/settings/properties/$objectType/$key/edit": typeof ProtectedWWorkspaceIdSettingsPropertiesObjectTypeKeyEditRoute
  "/w/$workspaceId/settings/properties/$objectType/new/$type": typeof ProtectedWWorkspaceIdSettingsPropertiesObjectTypeNewTypeRoute
  "/w/$workspaceId/settings/workspace/accept-invite/$wId/$inviteCode": typeof ProtectedWWorkspaceIdSettingsWorkspaceAcceptInviteWIdInviteCodeRoute
  "/w/$workspaceId/outreach/sequences/$id/contact-settings": typeof ProtectedWWorkspaceIdOutreachSequencesIdContactSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_protected": typeof ProtectedRouteRouteWithChildren
  "/local-redirect": typeof LocalRedirectRouteRoute
  "/cello": typeof CelloRoute
  "/custom-token-auth": typeof CustomTokenAuthRoute
  "/google-calendar-callback": typeof GoogleCalendarCallbackRoute
  "/payment-callback": typeof PaymentCallbackRoute
  "/_protected/": typeof ProtectedIndexRoute
  "/_protected/w/$workspaceId": typeof ProtectedWWorkspaceIdRouteRouteWithChildren
  "/_protected/mini-app/$": typeof ProtectedMiniAppSplatRoute
  "/_protected/accept-invite/$workspaceId/$inviteCode": typeof ProtectedAcceptInviteWorkspaceIdInviteCodeRoute
  "/_protected/w/$workspaceId/telegram": typeof ProtectedWWorkspaceIdTelegramRoute
  "/_protected/w/$workspaceId/": typeof ProtectedWWorkspaceIdIndexRoute
  "/_protected/w/$workspaceId/add-pending-activity/$id": typeof ProtectedWWorkspaceIdAddPendingActivityIdRoute
  "/_protected/w/$workspaceId/contacts/new": typeof ProtectedWWorkspaceIdContactsNewRoute
  "/_protected/w/$workspaceId/onboarding/$stepId": typeof ProtectedWWorkspaceIdOnboardingStepIdRoute
  "/_protected/w/$workspaceId/outreach/ai-bot": typeof ProtectedWWorkspaceIdOutreachAiBotRoute
  "/_protected/w/$workspaceId/outreach/schedule": typeof ProtectedWWorkspaceIdOutreachScheduleRoute
  "/_protected/w/$workspaceId/settings/affiliate": typeof ProtectedWWorkspaceIdSettingsAffiliateRoute
  "/_protected/w/$workspaceId/settings/connect-crm": typeof ProtectedWWorkspaceIdSettingsConnectCrmRoute
  "/_protected/w/$workspaceId/settings/export": typeof ProtectedWWorkspaceIdSettingsExportRoute
  "/_protected/w/$workspaceId/settings/feature-flags": typeof ProtectedWWorkspaceIdSettingsFeatureFlagsRoute
  "/_protected/w/$workspaceId/settings/google-calendar": typeof ProtectedWWorkspaceIdSettingsGoogleCalendarRoute
  "/_protected/w/$workspaceId/settings/help": typeof ProtectedWWorkspaceIdSettingsHelpRoute
  "/_protected/w/$workspaceId/settings/locale": typeof ProtectedWWorkspaceIdSettingsLocaleRoute
  "/_protected/w/$workspaceId/settings/notifications": typeof ProtectedWWorkspaceIdSettingsNotificationsRoute
  "/_protected/w/$workspaceId/settings/subscription": typeof ProtectedWWorkspaceIdSettingsSubscriptionRoute
  "/_protected/w/$workspaceId/settings/telegram-sync": typeof ProtectedWWorkspaceIdSettingsTelegramSyncRoute
  "/_protected/w/$workspaceId/tools/group-parser": typeof ProtectedWWorkspaceIdToolsGroupParserRoute
  "/_protected/w/$workspaceId/tools/lookalike-audience": typeof ProtectedWWorkspaceIdToolsLookalikeAudienceRoute
  "/_protected/w/$workspaceId/tools/phone-numbers-converter": typeof ProtectedWWorkspaceIdToolsPhoneNumbersConverterRoute
  "/_protected/w/$workspaceId/wallet/top-up": typeof ProtectedWWorkspaceIdWalletTopUpRoute
  "/_protected/w/$workspaceId/contacts/": typeof ProtectedWWorkspaceIdContactsIndexRoute
  "/_protected/w/$workspaceId/onboarding/": typeof ProtectedWWorkspaceIdOnboardingIndexRoute
  "/_protected/w/$workspaceId/outreach/": typeof ProtectedWWorkspaceIdOutreachIndexRoute
  "/_protected/w/$workspaceId/settings/": typeof ProtectedWWorkspaceIdSettingsIndexRoute
  "/_protected/w/$workspaceId/contacts/$contactId/edit": typeof ProtectedWWorkspaceIdContactsContactIdEditRoute
  "/_protected/w/$workspaceId/outreach/telegram-accounts/$accountId": typeof ProtectedWWorkspaceIdOutreachTelegramAccountsAccountIdRoute
  "/_protected/w/$workspaceId/outreach/telegram-accounts/buy": typeof ProtectedWWorkspaceIdOutreachTelegramAccountsBuyRoute
  "/_protected/w/$workspaceId/outreach/telegram-accounts/new": typeof ProtectedWWorkspaceIdOutreachTelegramAccountsNewRoute
  "/_protected/w/$workspaceId/settings/api-keys/$keyId": typeof ProtectedWWorkspaceIdSettingsApiKeysKeyIdRoute
  "/_protected/w/$workspaceId/settings/organization/$organizationId": typeof ProtectedWWorkspaceIdSettingsOrganizationOrganizationIdRoute
  "/_protected/w/$workspaceId/settings/workspace/invite": typeof ProtectedWWorkspaceIdSettingsWorkspaceInviteRoute
  "/_protected/w/$workspaceId/settings/workspace/new": typeof ProtectedWWorkspaceIdSettingsWorkspaceNewRoute
  "/_protected/w/$workspaceId/contacts/$contactId/": typeof ProtectedWWorkspaceIdContactsContactIdIndexRoute
  "/_protected/w/$workspaceId/outreach/telegram-accounts/": typeof ProtectedWWorkspaceIdOutreachTelegramAccountsIndexRoute
  "/_protected/w/$workspaceId/settings/api-keys/": typeof ProtectedWWorkspaceIdSettingsApiKeysIndexRoute
  "/_protected/w/$workspaceId/settings/workspace/": typeof ProtectedWWorkspaceIdSettingsWorkspaceIndexRoute
  "/_protected/w/$workspaceId/contacts/$contactId/activities/new": typeof ProtectedWWorkspaceIdContactsContactIdActivitiesNewRoute
  "/_protected/w/$workspaceId/outreach/sequences/$id/accounts": typeof ProtectedWWorkspaceIdOutreachSequencesIdAccountsRoute
  "/_protected/w/$workspaceId/outreach/sequences/$id/leads": typeof ProtectedWWorkspaceIdOutreachSequencesIdLeadsRoute
  "/_protected/w/$workspaceId/outreach/sequences/new/crm": typeof ProtectedWWorkspaceIdOutreachSequencesNewCrmRoute
  "/_protected/w/$workspaceId/outreach/sequences/new/csv": typeof ProtectedWWorkspaceIdOutreachSequencesNewCsvRoute
  "/_protected/w/$workspaceId/settings/api-keys/webhooks/$webhookId": typeof ProtectedWWorkspaceIdSettingsApiKeysWebhooksWebhookIdRoute
  "/_protected/w/$workspaceId/settings/workspace/user/$userId": typeof ProtectedWWorkspaceIdSettingsWorkspaceUserUserIdRoute
  "/_protected/w/$workspaceId/outreach/sequences/$id/": typeof ProtectedWWorkspaceIdOutreachSequencesIdIndexRoute
  "/_protected/w/$workspaceId/outreach/sequences/new/": typeof ProtectedWWorkspaceIdOutreachSequencesNewIndexRoute
  "/_protected/w/$workspaceId/settings/api-keys/webhooks/": typeof ProtectedWWorkspaceIdSettingsApiKeysWebhooksIndexRoute
  "/_protected/w/$workspaceId/settings/properties/$objectType/": typeof ProtectedWWorkspaceIdSettingsPropertiesObjectTypeIndexRoute
  "/_protected/w/$workspaceId/contacts/$contactId/activities/$activityId/edit": typeof ProtectedWWorkspaceIdContactsContactIdActivitiesActivityIdEditRoute
  "/_protected/w/$workspaceId/outreach/sequences/$id/contact-settings/owners": typeof ProtectedWWorkspaceIdOutreachSequencesIdContactSettingsOwnersRoute
  "/_protected/w/$workspaceId/settings/members/accept-invite/$wId/$inviteCode": typeof ProtectedWWorkspaceIdSettingsMembersAcceptInviteWIdInviteCodeRoute
  "/_protected/w/$workspaceId/settings/properties/$objectType/$key/edit": typeof ProtectedWWorkspaceIdSettingsPropertiesObjectTypeKeyEditRoute
  "/_protected/w/$workspaceId/settings/properties/$objectType/new/$type": typeof ProtectedWWorkspaceIdSettingsPropertiesObjectTypeNewTypeRoute
  "/_protected/w/$workspaceId/settings/workspace/accept-invite/$wId/$inviteCode": typeof ProtectedWWorkspaceIdSettingsWorkspaceAcceptInviteWIdInviteCodeRoute
  "/_protected/w/$workspaceId/outreach/sequences/$id/contact-settings/": typeof ProtectedWWorkspaceIdOutreachSequencesIdContactSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/local-redirect"
    | "/cello"
    | "/custom-token-auth"
    | "/google-calendar-callback"
    | "/payment-callback"
    | "/w/$workspaceId"
    | "/mini-app/$"
    | "/accept-invite/$workspaceId/$inviteCode"
    | "/w/$workspaceId/telegram"
    | "/w/$workspaceId/"
    | "/w/$workspaceId/add-pending-activity/$id"
    | "/w/$workspaceId/contacts/new"
    | "/w/$workspaceId/onboarding/$stepId"
    | "/w/$workspaceId/outreach/ai-bot"
    | "/w/$workspaceId/outreach/schedule"
    | "/w/$workspaceId/settings/affiliate"
    | "/w/$workspaceId/settings/connect-crm"
    | "/w/$workspaceId/settings/export"
    | "/w/$workspaceId/settings/feature-flags"
    | "/w/$workspaceId/settings/google-calendar"
    | "/w/$workspaceId/settings/help"
    | "/w/$workspaceId/settings/locale"
    | "/w/$workspaceId/settings/notifications"
    | "/w/$workspaceId/settings/subscription"
    | "/w/$workspaceId/settings/telegram-sync"
    | "/w/$workspaceId/tools/group-parser"
    | "/w/$workspaceId/tools/lookalike-audience"
    | "/w/$workspaceId/tools/phone-numbers-converter"
    | "/w/$workspaceId/wallet/top-up"
    | "/w/$workspaceId/contacts/"
    | "/w/$workspaceId/onboarding/"
    | "/w/$workspaceId/outreach/"
    | "/w/$workspaceId/settings/"
    | "/w/$workspaceId/contacts/$contactId/edit"
    | "/w/$workspaceId/outreach/telegram-accounts/$accountId"
    | "/w/$workspaceId/outreach/telegram-accounts/buy"
    | "/w/$workspaceId/outreach/telegram-accounts/new"
    | "/w/$workspaceId/settings/api-keys/$keyId"
    | "/w/$workspaceId/settings/organization/$organizationId"
    | "/w/$workspaceId/settings/workspace/invite"
    | "/w/$workspaceId/settings/workspace/new"
    | "/w/$workspaceId/contacts/$contactId/"
    | "/w/$workspaceId/outreach/telegram-accounts/"
    | "/w/$workspaceId/settings/api-keys/"
    | "/w/$workspaceId/settings/workspace/"
    | "/w/$workspaceId/contacts/$contactId/activities/new"
    | "/w/$workspaceId/outreach/sequences/$id/accounts"
    | "/w/$workspaceId/outreach/sequences/$id/leads"
    | "/w/$workspaceId/outreach/sequences/new/crm"
    | "/w/$workspaceId/outreach/sequences/new/csv"
    | "/w/$workspaceId/settings/api-keys/webhooks/$webhookId"
    | "/w/$workspaceId/settings/workspace/user/$userId"
    | "/w/$workspaceId/outreach/sequences/$id/"
    | "/w/$workspaceId/outreach/sequences/new/"
    | "/w/$workspaceId/settings/api-keys/webhooks/"
    | "/w/$workspaceId/settings/properties/$objectType/"
    | "/w/$workspaceId/contacts/$contactId/activities/$activityId/edit"
    | "/w/$workspaceId/outreach/sequences/$id/contact-settings/owners"
    | "/w/$workspaceId/settings/members/accept-invite/$wId/$inviteCode"
    | "/w/$workspaceId/settings/properties/$objectType/$key/edit"
    | "/w/$workspaceId/settings/properties/$objectType/new/$type"
    | "/w/$workspaceId/settings/workspace/accept-invite/$wId/$inviteCode"
    | "/w/$workspaceId/outreach/sequences/$id/contact-settings/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/local-redirect"
    | "/cello"
    | "/custom-token-auth"
    | "/google-calendar-callback"
    | "/payment-callback"
    | "/"
    | "/mini-app/$"
    | "/accept-invite/$workspaceId/$inviteCode"
    | "/w/$workspaceId/telegram"
    | "/w/$workspaceId"
    | "/w/$workspaceId/add-pending-activity/$id"
    | "/w/$workspaceId/contacts/new"
    | "/w/$workspaceId/onboarding/$stepId"
    | "/w/$workspaceId/outreach/ai-bot"
    | "/w/$workspaceId/outreach/schedule"
    | "/w/$workspaceId/settings/affiliate"
    | "/w/$workspaceId/settings/connect-crm"
    | "/w/$workspaceId/settings/export"
    | "/w/$workspaceId/settings/feature-flags"
    | "/w/$workspaceId/settings/google-calendar"
    | "/w/$workspaceId/settings/help"
    | "/w/$workspaceId/settings/locale"
    | "/w/$workspaceId/settings/notifications"
    | "/w/$workspaceId/settings/subscription"
    | "/w/$workspaceId/settings/telegram-sync"
    | "/w/$workspaceId/tools/group-parser"
    | "/w/$workspaceId/tools/lookalike-audience"
    | "/w/$workspaceId/tools/phone-numbers-converter"
    | "/w/$workspaceId/wallet/top-up"
    | "/w/$workspaceId/contacts"
    | "/w/$workspaceId/onboarding"
    | "/w/$workspaceId/outreach"
    | "/w/$workspaceId/settings"
    | "/w/$workspaceId/contacts/$contactId/edit"
    | "/w/$workspaceId/outreach/telegram-accounts/$accountId"
    | "/w/$workspaceId/outreach/telegram-accounts/buy"
    | "/w/$workspaceId/outreach/telegram-accounts/new"
    | "/w/$workspaceId/settings/api-keys/$keyId"
    | "/w/$workspaceId/settings/organization/$organizationId"
    | "/w/$workspaceId/settings/workspace/invite"
    | "/w/$workspaceId/settings/workspace/new"
    | "/w/$workspaceId/contacts/$contactId"
    | "/w/$workspaceId/outreach/telegram-accounts"
    | "/w/$workspaceId/settings/api-keys"
    | "/w/$workspaceId/settings/workspace"
    | "/w/$workspaceId/contacts/$contactId/activities/new"
    | "/w/$workspaceId/outreach/sequences/$id/accounts"
    | "/w/$workspaceId/outreach/sequences/$id/leads"
    | "/w/$workspaceId/outreach/sequences/new/crm"
    | "/w/$workspaceId/outreach/sequences/new/csv"
    | "/w/$workspaceId/settings/api-keys/webhooks/$webhookId"
    | "/w/$workspaceId/settings/workspace/user/$userId"
    | "/w/$workspaceId/outreach/sequences/$id"
    | "/w/$workspaceId/outreach/sequences/new"
    | "/w/$workspaceId/settings/api-keys/webhooks"
    | "/w/$workspaceId/settings/properties/$objectType"
    | "/w/$workspaceId/contacts/$contactId/activities/$activityId/edit"
    | "/w/$workspaceId/outreach/sequences/$id/contact-settings/owners"
    | "/w/$workspaceId/settings/members/accept-invite/$wId/$inviteCode"
    | "/w/$workspaceId/settings/properties/$objectType/$key/edit"
    | "/w/$workspaceId/settings/properties/$objectType/new/$type"
    | "/w/$workspaceId/settings/workspace/accept-invite/$wId/$inviteCode"
    | "/w/$workspaceId/outreach/sequences/$id/contact-settings"
  id:
    | "__root__"
    | "/_protected"
    | "/local-redirect"
    | "/cello"
    | "/custom-token-auth"
    | "/google-calendar-callback"
    | "/payment-callback"
    | "/_protected/"
    | "/_protected/w/$workspaceId"
    | "/_protected/mini-app/$"
    | "/_protected/accept-invite/$workspaceId/$inviteCode"
    | "/_protected/w/$workspaceId/telegram"
    | "/_protected/w/$workspaceId/"
    | "/_protected/w/$workspaceId/add-pending-activity/$id"
    | "/_protected/w/$workspaceId/contacts/new"
    | "/_protected/w/$workspaceId/onboarding/$stepId"
    | "/_protected/w/$workspaceId/outreach/ai-bot"
    | "/_protected/w/$workspaceId/outreach/schedule"
    | "/_protected/w/$workspaceId/settings/affiliate"
    | "/_protected/w/$workspaceId/settings/connect-crm"
    | "/_protected/w/$workspaceId/settings/export"
    | "/_protected/w/$workspaceId/settings/feature-flags"
    | "/_protected/w/$workspaceId/settings/google-calendar"
    | "/_protected/w/$workspaceId/settings/help"
    | "/_protected/w/$workspaceId/settings/locale"
    | "/_protected/w/$workspaceId/settings/notifications"
    | "/_protected/w/$workspaceId/settings/subscription"
    | "/_protected/w/$workspaceId/settings/telegram-sync"
    | "/_protected/w/$workspaceId/tools/group-parser"
    | "/_protected/w/$workspaceId/tools/lookalike-audience"
    | "/_protected/w/$workspaceId/tools/phone-numbers-converter"
    | "/_protected/w/$workspaceId/wallet/top-up"
    | "/_protected/w/$workspaceId/contacts/"
    | "/_protected/w/$workspaceId/onboarding/"
    | "/_protected/w/$workspaceId/outreach/"
    | "/_protected/w/$workspaceId/settings/"
    | "/_protected/w/$workspaceId/contacts/$contactId/edit"
    | "/_protected/w/$workspaceId/outreach/telegram-accounts/$accountId"
    | "/_protected/w/$workspaceId/outreach/telegram-accounts/buy"
    | "/_protected/w/$workspaceId/outreach/telegram-accounts/new"
    | "/_protected/w/$workspaceId/settings/api-keys/$keyId"
    | "/_protected/w/$workspaceId/settings/organization/$organizationId"
    | "/_protected/w/$workspaceId/settings/workspace/invite"
    | "/_protected/w/$workspaceId/settings/workspace/new"
    | "/_protected/w/$workspaceId/contacts/$contactId/"
    | "/_protected/w/$workspaceId/outreach/telegram-accounts/"
    | "/_protected/w/$workspaceId/settings/api-keys/"
    | "/_protected/w/$workspaceId/settings/workspace/"
    | "/_protected/w/$workspaceId/contacts/$contactId/activities/new"
    | "/_protected/w/$workspaceId/outreach/sequences/$id/accounts"
    | "/_protected/w/$workspaceId/outreach/sequences/$id/leads"
    | "/_protected/w/$workspaceId/outreach/sequences/new/crm"
    | "/_protected/w/$workspaceId/outreach/sequences/new/csv"
    | "/_protected/w/$workspaceId/settings/api-keys/webhooks/$webhookId"
    | "/_protected/w/$workspaceId/settings/workspace/user/$userId"
    | "/_protected/w/$workspaceId/outreach/sequences/$id/"
    | "/_protected/w/$workspaceId/outreach/sequences/new/"
    | "/_protected/w/$workspaceId/settings/api-keys/webhooks/"
    | "/_protected/w/$workspaceId/settings/properties/$objectType/"
    | "/_protected/w/$workspaceId/contacts/$contactId/activities/$activityId/edit"
    | "/_protected/w/$workspaceId/outreach/sequences/$id/contact-settings/owners"
    | "/_protected/w/$workspaceId/settings/members/accept-invite/$wId/$inviteCode"
    | "/_protected/w/$workspaceId/settings/properties/$objectType/$key/edit"
    | "/_protected/w/$workspaceId/settings/properties/$objectType/new/$type"
    | "/_protected/w/$workspaceId/settings/workspace/accept-invite/$wId/$inviteCode"
    | "/_protected/w/$workspaceId/outreach/sequences/$id/contact-settings/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  LocalRedirectRouteRoute: typeof LocalRedirectRouteRoute
  CelloRoute: typeof CelloRoute
  CustomTokenAuthRoute: typeof CustomTokenAuthRoute
  GoogleCalendarCallbackRoute: typeof GoogleCalendarCallbackRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/payment-callback": {
      id: "/payment-callback"
      path: "/payment-callback"
      fullPath: "/payment-callback"
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/google-calendar-callback": {
      id: "/google-calendar-callback"
      path: "/google-calendar-callback"
      fullPath: "/google-calendar-callback"
      preLoaderRoute: typeof GoogleCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/custom-token-auth": {
      id: "/custom-token-auth"
      path: "/custom-token-auth"
      fullPath: "/custom-token-auth"
      preLoaderRoute: typeof CustomTokenAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/cello": {
      id: "/cello"
      path: "/cello"
      fullPath: "/cello"
      preLoaderRoute: typeof CelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/local-redirect": {
      id: "/local-redirect"
      path: "/local-redirect"
      fullPath: "/local-redirect"
      preLoaderRoute: typeof LocalRedirectRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_protected": {
      id: "/_protected"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_protected/": {
      id: "/_protected/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    "/_protected/mini-app/$": {
      id: "/_protected/mini-app/$"
      path: "/mini-app/$"
      fullPath: "/mini-app/$"
      preLoaderRoute: typeof ProtectedMiniAppSplatRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    "/_protected/w/$workspaceId": {
      id: "/_protected/w/$workspaceId"
      path: "/w/$workspaceId"
      fullPath: "/w/$workspaceId"
      preLoaderRoute: typeof ProtectedWWorkspaceIdRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    "/_protected/w/$workspaceId/": {
      id: "/_protected/w/$workspaceId/"
      path: "/"
      fullPath: "/w/$workspaceId/"
      preLoaderRoute: typeof ProtectedWWorkspaceIdIndexRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/telegram": {
      id: "/_protected/w/$workspaceId/telegram"
      path: "/telegram"
      fullPath: "/w/$workspaceId/telegram"
      preLoaderRoute: typeof ProtectedWWorkspaceIdTelegramRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/accept-invite/$workspaceId/$inviteCode": {
      id: "/_protected/accept-invite/$workspaceId/$inviteCode"
      path: "/accept-invite/$workspaceId/$inviteCode"
      fullPath: "/accept-invite/$workspaceId/$inviteCode"
      preLoaderRoute: typeof ProtectedAcceptInviteWorkspaceIdInviteCodeRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    "/_protected/w/$workspaceId/settings/": {
      id: "/_protected/w/$workspaceId/settings/"
      path: "/settings"
      fullPath: "/w/$workspaceId/settings/"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsIndexRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/outreach/": {
      id: "/_protected/w/$workspaceId/outreach/"
      path: "/outreach"
      fullPath: "/w/$workspaceId/outreach/"
      preLoaderRoute: typeof ProtectedWWorkspaceIdOutreachIndexRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/onboarding/": {
      id: "/_protected/w/$workspaceId/onboarding/"
      path: "/onboarding"
      fullPath: "/w/$workspaceId/onboarding/"
      preLoaderRoute: typeof ProtectedWWorkspaceIdOnboardingIndexRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/contacts/": {
      id: "/_protected/w/$workspaceId/contacts/"
      path: "/contacts"
      fullPath: "/w/$workspaceId/contacts/"
      preLoaderRoute: typeof ProtectedWWorkspaceIdContactsIndexRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/wallet/top-up": {
      id: "/_protected/w/$workspaceId/wallet/top-up"
      path: "/wallet/top-up"
      fullPath: "/w/$workspaceId/wallet/top-up"
      preLoaderRoute: typeof ProtectedWWorkspaceIdWalletTopUpRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/tools/phone-numbers-converter": {
      id: "/_protected/w/$workspaceId/tools/phone-numbers-converter"
      path: "/tools/phone-numbers-converter"
      fullPath: "/w/$workspaceId/tools/phone-numbers-converter"
      preLoaderRoute: typeof ProtectedWWorkspaceIdToolsPhoneNumbersConverterRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/tools/lookalike-audience": {
      id: "/_protected/w/$workspaceId/tools/lookalike-audience"
      path: "/tools/lookalike-audience"
      fullPath: "/w/$workspaceId/tools/lookalike-audience"
      preLoaderRoute: typeof ProtectedWWorkspaceIdToolsLookalikeAudienceRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/tools/group-parser": {
      id: "/_protected/w/$workspaceId/tools/group-parser"
      path: "/tools/group-parser"
      fullPath: "/w/$workspaceId/tools/group-parser"
      preLoaderRoute: typeof ProtectedWWorkspaceIdToolsGroupParserRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/settings/telegram-sync": {
      id: "/_protected/w/$workspaceId/settings/telegram-sync"
      path: "/settings/telegram-sync"
      fullPath: "/w/$workspaceId/settings/telegram-sync"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsTelegramSyncRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/settings/subscription": {
      id: "/_protected/w/$workspaceId/settings/subscription"
      path: "/settings/subscription"
      fullPath: "/w/$workspaceId/settings/subscription"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsSubscriptionRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/settings/notifications": {
      id: "/_protected/w/$workspaceId/settings/notifications"
      path: "/settings/notifications"
      fullPath: "/w/$workspaceId/settings/notifications"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsNotificationsRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/settings/locale": {
      id: "/_protected/w/$workspaceId/settings/locale"
      path: "/settings/locale"
      fullPath: "/w/$workspaceId/settings/locale"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsLocaleRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/settings/help": {
      id: "/_protected/w/$workspaceId/settings/help"
      path: "/settings/help"
      fullPath: "/w/$workspaceId/settings/help"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsHelpRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/settings/google-calendar": {
      id: "/_protected/w/$workspaceId/settings/google-calendar"
      path: "/settings/google-calendar"
      fullPath: "/w/$workspaceId/settings/google-calendar"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsGoogleCalendarRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/settings/feature-flags": {
      id: "/_protected/w/$workspaceId/settings/feature-flags"
      path: "/settings/feature-flags"
      fullPath: "/w/$workspaceId/settings/feature-flags"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsFeatureFlagsRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/settings/export": {
      id: "/_protected/w/$workspaceId/settings/export"
      path: "/settings/export"
      fullPath: "/w/$workspaceId/settings/export"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsExportRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/settings/connect-crm": {
      id: "/_protected/w/$workspaceId/settings/connect-crm"
      path: "/settings/connect-crm"
      fullPath: "/w/$workspaceId/settings/connect-crm"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsConnectCrmRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/settings/affiliate": {
      id: "/_protected/w/$workspaceId/settings/affiliate"
      path: "/settings/affiliate"
      fullPath: "/w/$workspaceId/settings/affiliate"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsAffiliateRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/outreach/schedule": {
      id: "/_protected/w/$workspaceId/outreach/schedule"
      path: "/outreach/schedule"
      fullPath: "/w/$workspaceId/outreach/schedule"
      preLoaderRoute: typeof ProtectedWWorkspaceIdOutreachScheduleRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/outreach/ai-bot": {
      id: "/_protected/w/$workspaceId/outreach/ai-bot"
      path: "/outreach/ai-bot"
      fullPath: "/w/$workspaceId/outreach/ai-bot"
      preLoaderRoute: typeof ProtectedWWorkspaceIdOutreachAiBotRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/onboarding/$stepId": {
      id: "/_protected/w/$workspaceId/onboarding/$stepId"
      path: "/onboarding/$stepId"
      fullPath: "/w/$workspaceId/onboarding/$stepId"
      preLoaderRoute: typeof ProtectedWWorkspaceIdOnboardingStepIdRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/contacts/new": {
      id: "/_protected/w/$workspaceId/contacts/new"
      path: "/contacts/new"
      fullPath: "/w/$workspaceId/contacts/new"
      preLoaderRoute: typeof ProtectedWWorkspaceIdContactsNewRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/add-pending-activity/$id": {
      id: "/_protected/w/$workspaceId/add-pending-activity/$id"
      path: "/add-pending-activity/$id"
      fullPath: "/w/$workspaceId/add-pending-activity/$id"
      preLoaderRoute: typeof ProtectedWWorkspaceIdAddPendingActivityIdRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/settings/workspace/": {
      id: "/_protected/w/$workspaceId/settings/workspace/"
      path: "/settings/workspace"
      fullPath: "/w/$workspaceId/settings/workspace/"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsWorkspaceIndexRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/settings/api-keys/": {
      id: "/_protected/w/$workspaceId/settings/api-keys/"
      path: "/settings/api-keys"
      fullPath: "/w/$workspaceId/settings/api-keys/"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsApiKeysIndexRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/outreach/telegram-accounts/": {
      id: "/_protected/w/$workspaceId/outreach/telegram-accounts/"
      path: "/outreach/telegram-accounts"
      fullPath: "/w/$workspaceId/outreach/telegram-accounts/"
      preLoaderRoute: typeof ProtectedWWorkspaceIdOutreachTelegramAccountsIndexRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/contacts/$contactId/": {
      id: "/_protected/w/$workspaceId/contacts/$contactId/"
      path: "/contacts/$contactId"
      fullPath: "/w/$workspaceId/contacts/$contactId/"
      preLoaderRoute: typeof ProtectedWWorkspaceIdContactsContactIdIndexRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/settings/workspace/new": {
      id: "/_protected/w/$workspaceId/settings/workspace/new"
      path: "/settings/workspace/new"
      fullPath: "/w/$workspaceId/settings/workspace/new"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsWorkspaceNewRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/settings/workspace/invite": {
      id: "/_protected/w/$workspaceId/settings/workspace/invite"
      path: "/settings/workspace/invite"
      fullPath: "/w/$workspaceId/settings/workspace/invite"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsWorkspaceInviteRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/settings/organization/$organizationId": {
      id: "/_protected/w/$workspaceId/settings/organization/$organizationId"
      path: "/settings/organization/$organizationId"
      fullPath: "/w/$workspaceId/settings/organization/$organizationId"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsOrganizationOrganizationIdRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/settings/api-keys/$keyId": {
      id: "/_protected/w/$workspaceId/settings/api-keys/$keyId"
      path: "/settings/api-keys/$keyId"
      fullPath: "/w/$workspaceId/settings/api-keys/$keyId"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsApiKeysKeyIdRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/outreach/telegram-accounts/new": {
      id: "/_protected/w/$workspaceId/outreach/telegram-accounts/new"
      path: "/outreach/telegram-accounts/new"
      fullPath: "/w/$workspaceId/outreach/telegram-accounts/new"
      preLoaderRoute: typeof ProtectedWWorkspaceIdOutreachTelegramAccountsNewRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/outreach/telegram-accounts/buy": {
      id: "/_protected/w/$workspaceId/outreach/telegram-accounts/buy"
      path: "/outreach/telegram-accounts/buy"
      fullPath: "/w/$workspaceId/outreach/telegram-accounts/buy"
      preLoaderRoute: typeof ProtectedWWorkspaceIdOutreachTelegramAccountsBuyRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/outreach/telegram-accounts/$accountId": {
      id: "/_protected/w/$workspaceId/outreach/telegram-accounts/$accountId"
      path: "/outreach/telegram-accounts/$accountId"
      fullPath: "/w/$workspaceId/outreach/telegram-accounts/$accountId"
      preLoaderRoute: typeof ProtectedWWorkspaceIdOutreachTelegramAccountsAccountIdRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/contacts/$contactId/edit": {
      id: "/_protected/w/$workspaceId/contacts/$contactId/edit"
      path: "/contacts/$contactId/edit"
      fullPath: "/w/$workspaceId/contacts/$contactId/edit"
      preLoaderRoute: typeof ProtectedWWorkspaceIdContactsContactIdEditRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/settings/properties/$objectType/": {
      id: "/_protected/w/$workspaceId/settings/properties/$objectType/"
      path: "/settings/properties/$objectType"
      fullPath: "/w/$workspaceId/settings/properties/$objectType/"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsPropertiesObjectTypeIndexRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/settings/api-keys/webhooks/": {
      id: "/_protected/w/$workspaceId/settings/api-keys/webhooks/"
      path: "/settings/api-keys/webhooks"
      fullPath: "/w/$workspaceId/settings/api-keys/webhooks/"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsApiKeysWebhooksIndexRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/outreach/sequences/new/": {
      id: "/_protected/w/$workspaceId/outreach/sequences/new/"
      path: "/outreach/sequences/new"
      fullPath: "/w/$workspaceId/outreach/sequences/new/"
      preLoaderRoute: typeof ProtectedWWorkspaceIdOutreachSequencesNewIndexRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/outreach/sequences/$id/": {
      id: "/_protected/w/$workspaceId/outreach/sequences/$id/"
      path: "/outreach/sequences/$id"
      fullPath: "/w/$workspaceId/outreach/sequences/$id/"
      preLoaderRoute: typeof ProtectedWWorkspaceIdOutreachSequencesIdIndexRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/settings/workspace/user/$userId": {
      id: "/_protected/w/$workspaceId/settings/workspace/user/$userId"
      path: "/settings/workspace/user/$userId"
      fullPath: "/w/$workspaceId/settings/workspace/user/$userId"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsWorkspaceUserUserIdRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/settings/api-keys/webhooks/$webhookId": {
      id: "/_protected/w/$workspaceId/settings/api-keys/webhooks/$webhookId"
      path: "/settings/api-keys/webhooks/$webhookId"
      fullPath: "/w/$workspaceId/settings/api-keys/webhooks/$webhookId"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsApiKeysWebhooksWebhookIdRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/outreach/sequences/new/csv": {
      id: "/_protected/w/$workspaceId/outreach/sequences/new/csv"
      path: "/outreach/sequences/new/csv"
      fullPath: "/w/$workspaceId/outreach/sequences/new/csv"
      preLoaderRoute: typeof ProtectedWWorkspaceIdOutreachSequencesNewCsvRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/outreach/sequences/new/crm": {
      id: "/_protected/w/$workspaceId/outreach/sequences/new/crm"
      path: "/outreach/sequences/new/crm"
      fullPath: "/w/$workspaceId/outreach/sequences/new/crm"
      preLoaderRoute: typeof ProtectedWWorkspaceIdOutreachSequencesNewCrmRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/outreach/sequences/$id/leads": {
      id: "/_protected/w/$workspaceId/outreach/sequences/$id/leads"
      path: "/outreach/sequences/$id/leads"
      fullPath: "/w/$workspaceId/outreach/sequences/$id/leads"
      preLoaderRoute: typeof ProtectedWWorkspaceIdOutreachSequencesIdLeadsRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/outreach/sequences/$id/accounts": {
      id: "/_protected/w/$workspaceId/outreach/sequences/$id/accounts"
      path: "/outreach/sequences/$id/accounts"
      fullPath: "/w/$workspaceId/outreach/sequences/$id/accounts"
      preLoaderRoute: typeof ProtectedWWorkspaceIdOutreachSequencesIdAccountsRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/contacts/$contactId/activities/new": {
      id: "/_protected/w/$workspaceId/contacts/$contactId/activities/new"
      path: "/contacts/$contactId/activities/new"
      fullPath: "/w/$workspaceId/contacts/$contactId/activities/new"
      preLoaderRoute: typeof ProtectedWWorkspaceIdContactsContactIdActivitiesNewRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/outreach/sequences/$id/contact-settings/": {
      id: "/_protected/w/$workspaceId/outreach/sequences/$id/contact-settings/"
      path: "/outreach/sequences/$id/contact-settings"
      fullPath: "/w/$workspaceId/outreach/sequences/$id/contact-settings/"
      preLoaderRoute: typeof ProtectedWWorkspaceIdOutreachSequencesIdContactSettingsIndexRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/settings/workspace/accept-invite/$wId/$inviteCode": {
      id: "/_protected/w/$workspaceId/settings/workspace/accept-invite/$wId/$inviteCode"
      path: "/settings/workspace/accept-invite/$wId/$inviteCode"
      fullPath: "/w/$workspaceId/settings/workspace/accept-invite/$wId/$inviteCode"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsWorkspaceAcceptInviteWIdInviteCodeRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/settings/properties/$objectType/new/$type": {
      id: "/_protected/w/$workspaceId/settings/properties/$objectType/new/$type"
      path: "/settings/properties/$objectType/new/$type"
      fullPath: "/w/$workspaceId/settings/properties/$objectType/new/$type"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsPropertiesObjectTypeNewTypeRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/settings/properties/$objectType/$key/edit": {
      id: "/_protected/w/$workspaceId/settings/properties/$objectType/$key/edit"
      path: "/settings/properties/$objectType/$key/edit"
      fullPath: "/w/$workspaceId/settings/properties/$objectType/$key/edit"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsPropertiesObjectTypeKeyEditRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/settings/members/accept-invite/$wId/$inviteCode": {
      id: "/_protected/w/$workspaceId/settings/members/accept-invite/$wId/$inviteCode"
      path: "/settings/members/accept-invite/$wId/$inviteCode"
      fullPath: "/w/$workspaceId/settings/members/accept-invite/$wId/$inviteCode"
      preLoaderRoute: typeof ProtectedWWorkspaceIdSettingsMembersAcceptInviteWIdInviteCodeRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/outreach/sequences/$id/contact-settings/owners": {
      id: "/_protected/w/$workspaceId/outreach/sequences/$id/contact-settings/owners"
      path: "/outreach/sequences/$id/contact-settings/owners"
      fullPath: "/w/$workspaceId/outreach/sequences/$id/contact-settings/owners"
      preLoaderRoute: typeof ProtectedWWorkspaceIdOutreachSequencesIdContactSettingsOwnersRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
    "/_protected/w/$workspaceId/contacts/$contactId/activities/$activityId/edit": {
      id: "/_protected/w/$workspaceId/contacts/$contactId/activities/$activityId/edit"
      path: "/contacts/$contactId/activities/$activityId/edit"
      fullPath: "/w/$workspaceId/contacts/$contactId/activities/$activityId/edit"
      preLoaderRoute: typeof ProtectedWWorkspaceIdContactsContactIdActivitiesActivityIdEditRouteImport
      parentRoute: typeof ProtectedWWorkspaceIdRouteRoute
    }
  }
}

interface ProtectedWWorkspaceIdRouteRouteChildren {
  ProtectedWWorkspaceIdTelegramRoute: typeof ProtectedWWorkspaceIdTelegramRoute
  ProtectedWWorkspaceIdIndexRoute: typeof ProtectedWWorkspaceIdIndexRoute
  ProtectedWWorkspaceIdAddPendingActivityIdRoute: typeof ProtectedWWorkspaceIdAddPendingActivityIdRoute
  ProtectedWWorkspaceIdContactsNewRoute: typeof ProtectedWWorkspaceIdContactsNewRoute
  ProtectedWWorkspaceIdOnboardingStepIdRoute: typeof ProtectedWWorkspaceIdOnboardingStepIdRoute
  ProtectedWWorkspaceIdOutreachAiBotRoute: typeof ProtectedWWorkspaceIdOutreachAiBotRoute
  ProtectedWWorkspaceIdOutreachScheduleRoute: typeof ProtectedWWorkspaceIdOutreachScheduleRoute
  ProtectedWWorkspaceIdSettingsAffiliateRoute: typeof ProtectedWWorkspaceIdSettingsAffiliateRoute
  ProtectedWWorkspaceIdSettingsConnectCrmRoute: typeof ProtectedWWorkspaceIdSettingsConnectCrmRoute
  ProtectedWWorkspaceIdSettingsExportRoute: typeof ProtectedWWorkspaceIdSettingsExportRoute
  ProtectedWWorkspaceIdSettingsFeatureFlagsRoute: typeof ProtectedWWorkspaceIdSettingsFeatureFlagsRoute
  ProtectedWWorkspaceIdSettingsGoogleCalendarRoute: typeof ProtectedWWorkspaceIdSettingsGoogleCalendarRoute
  ProtectedWWorkspaceIdSettingsHelpRoute: typeof ProtectedWWorkspaceIdSettingsHelpRoute
  ProtectedWWorkspaceIdSettingsLocaleRoute: typeof ProtectedWWorkspaceIdSettingsLocaleRoute
  ProtectedWWorkspaceIdSettingsNotificationsRoute: typeof ProtectedWWorkspaceIdSettingsNotificationsRoute
  ProtectedWWorkspaceIdSettingsSubscriptionRoute: typeof ProtectedWWorkspaceIdSettingsSubscriptionRoute
  ProtectedWWorkspaceIdSettingsTelegramSyncRoute: typeof ProtectedWWorkspaceIdSettingsTelegramSyncRoute
  ProtectedWWorkspaceIdToolsGroupParserRoute: typeof ProtectedWWorkspaceIdToolsGroupParserRoute
  ProtectedWWorkspaceIdToolsLookalikeAudienceRoute: typeof ProtectedWWorkspaceIdToolsLookalikeAudienceRoute
  ProtectedWWorkspaceIdToolsPhoneNumbersConverterRoute: typeof ProtectedWWorkspaceIdToolsPhoneNumbersConverterRoute
  ProtectedWWorkspaceIdWalletTopUpRoute: typeof ProtectedWWorkspaceIdWalletTopUpRoute
  ProtectedWWorkspaceIdContactsIndexRoute: typeof ProtectedWWorkspaceIdContactsIndexRoute
  ProtectedWWorkspaceIdOnboardingIndexRoute: typeof ProtectedWWorkspaceIdOnboardingIndexRoute
  ProtectedWWorkspaceIdOutreachIndexRoute: typeof ProtectedWWorkspaceIdOutreachIndexRoute
  ProtectedWWorkspaceIdSettingsIndexRoute: typeof ProtectedWWorkspaceIdSettingsIndexRoute
  ProtectedWWorkspaceIdContactsContactIdEditRoute: typeof ProtectedWWorkspaceIdContactsContactIdEditRoute
  ProtectedWWorkspaceIdOutreachTelegramAccountsAccountIdRoute: typeof ProtectedWWorkspaceIdOutreachTelegramAccountsAccountIdRoute
  ProtectedWWorkspaceIdOutreachTelegramAccountsBuyRoute: typeof ProtectedWWorkspaceIdOutreachTelegramAccountsBuyRoute
  ProtectedWWorkspaceIdOutreachTelegramAccountsNewRoute: typeof ProtectedWWorkspaceIdOutreachTelegramAccountsNewRoute
  ProtectedWWorkspaceIdSettingsApiKeysKeyIdRoute: typeof ProtectedWWorkspaceIdSettingsApiKeysKeyIdRoute
  ProtectedWWorkspaceIdSettingsOrganizationOrganizationIdRoute: typeof ProtectedWWorkspaceIdSettingsOrganizationOrganizationIdRoute
  ProtectedWWorkspaceIdSettingsWorkspaceInviteRoute: typeof ProtectedWWorkspaceIdSettingsWorkspaceInviteRoute
  ProtectedWWorkspaceIdSettingsWorkspaceNewRoute: typeof ProtectedWWorkspaceIdSettingsWorkspaceNewRoute
  ProtectedWWorkspaceIdContactsContactIdIndexRoute: typeof ProtectedWWorkspaceIdContactsContactIdIndexRoute
  ProtectedWWorkspaceIdOutreachTelegramAccountsIndexRoute: typeof ProtectedWWorkspaceIdOutreachTelegramAccountsIndexRoute
  ProtectedWWorkspaceIdSettingsApiKeysIndexRoute: typeof ProtectedWWorkspaceIdSettingsApiKeysIndexRoute
  ProtectedWWorkspaceIdSettingsWorkspaceIndexRoute: typeof ProtectedWWorkspaceIdSettingsWorkspaceIndexRoute
  ProtectedWWorkspaceIdContactsContactIdActivitiesNewRoute: typeof ProtectedWWorkspaceIdContactsContactIdActivitiesNewRoute
  ProtectedWWorkspaceIdOutreachSequencesIdAccountsRoute: typeof ProtectedWWorkspaceIdOutreachSequencesIdAccountsRoute
  ProtectedWWorkspaceIdOutreachSequencesIdLeadsRoute: typeof ProtectedWWorkspaceIdOutreachSequencesIdLeadsRoute
  ProtectedWWorkspaceIdOutreachSequencesNewCrmRoute: typeof ProtectedWWorkspaceIdOutreachSequencesNewCrmRoute
  ProtectedWWorkspaceIdOutreachSequencesNewCsvRoute: typeof ProtectedWWorkspaceIdOutreachSequencesNewCsvRoute
  ProtectedWWorkspaceIdSettingsApiKeysWebhooksWebhookIdRoute: typeof ProtectedWWorkspaceIdSettingsApiKeysWebhooksWebhookIdRoute
  ProtectedWWorkspaceIdSettingsWorkspaceUserUserIdRoute: typeof ProtectedWWorkspaceIdSettingsWorkspaceUserUserIdRoute
  ProtectedWWorkspaceIdOutreachSequencesIdIndexRoute: typeof ProtectedWWorkspaceIdOutreachSequencesIdIndexRoute
  ProtectedWWorkspaceIdOutreachSequencesNewIndexRoute: typeof ProtectedWWorkspaceIdOutreachSequencesNewIndexRoute
  ProtectedWWorkspaceIdSettingsApiKeysWebhooksIndexRoute: typeof ProtectedWWorkspaceIdSettingsApiKeysWebhooksIndexRoute
  ProtectedWWorkspaceIdSettingsPropertiesObjectTypeIndexRoute: typeof ProtectedWWorkspaceIdSettingsPropertiesObjectTypeIndexRoute
  ProtectedWWorkspaceIdContactsContactIdActivitiesActivityIdEditRoute: typeof ProtectedWWorkspaceIdContactsContactIdActivitiesActivityIdEditRoute
  ProtectedWWorkspaceIdOutreachSequencesIdContactSettingsOwnersRoute: typeof ProtectedWWorkspaceIdOutreachSequencesIdContactSettingsOwnersRoute
  ProtectedWWorkspaceIdSettingsMembersAcceptInviteWIdInviteCodeRoute: typeof ProtectedWWorkspaceIdSettingsMembersAcceptInviteWIdInviteCodeRoute
  ProtectedWWorkspaceIdSettingsPropertiesObjectTypeKeyEditRoute: typeof ProtectedWWorkspaceIdSettingsPropertiesObjectTypeKeyEditRoute
  ProtectedWWorkspaceIdSettingsPropertiesObjectTypeNewTypeRoute: typeof ProtectedWWorkspaceIdSettingsPropertiesObjectTypeNewTypeRoute
  ProtectedWWorkspaceIdSettingsWorkspaceAcceptInviteWIdInviteCodeRoute: typeof ProtectedWWorkspaceIdSettingsWorkspaceAcceptInviteWIdInviteCodeRoute
  ProtectedWWorkspaceIdOutreachSequencesIdContactSettingsIndexRoute: typeof ProtectedWWorkspaceIdOutreachSequencesIdContactSettingsIndexRoute
}

const ProtectedWWorkspaceIdRouteRouteChildren: ProtectedWWorkspaceIdRouteRouteChildren =
  {
    ProtectedWWorkspaceIdTelegramRoute: ProtectedWWorkspaceIdTelegramRoute,
    ProtectedWWorkspaceIdIndexRoute: ProtectedWWorkspaceIdIndexRoute,
    ProtectedWWorkspaceIdAddPendingActivityIdRoute:
      ProtectedWWorkspaceIdAddPendingActivityIdRoute,
    ProtectedWWorkspaceIdContactsNewRoute:
      ProtectedWWorkspaceIdContactsNewRoute,
    ProtectedWWorkspaceIdOnboardingStepIdRoute:
      ProtectedWWorkspaceIdOnboardingStepIdRoute,
    ProtectedWWorkspaceIdOutreachAiBotRoute:
      ProtectedWWorkspaceIdOutreachAiBotRoute,
    ProtectedWWorkspaceIdOutreachScheduleRoute:
      ProtectedWWorkspaceIdOutreachScheduleRoute,
    ProtectedWWorkspaceIdSettingsAffiliateRoute:
      ProtectedWWorkspaceIdSettingsAffiliateRoute,
    ProtectedWWorkspaceIdSettingsConnectCrmRoute:
      ProtectedWWorkspaceIdSettingsConnectCrmRoute,
    ProtectedWWorkspaceIdSettingsExportRoute:
      ProtectedWWorkspaceIdSettingsExportRoute,
    ProtectedWWorkspaceIdSettingsFeatureFlagsRoute:
      ProtectedWWorkspaceIdSettingsFeatureFlagsRoute,
    ProtectedWWorkspaceIdSettingsGoogleCalendarRoute:
      ProtectedWWorkspaceIdSettingsGoogleCalendarRoute,
    ProtectedWWorkspaceIdSettingsHelpRoute:
      ProtectedWWorkspaceIdSettingsHelpRoute,
    ProtectedWWorkspaceIdSettingsLocaleRoute:
      ProtectedWWorkspaceIdSettingsLocaleRoute,
    ProtectedWWorkspaceIdSettingsNotificationsRoute:
      ProtectedWWorkspaceIdSettingsNotificationsRoute,
    ProtectedWWorkspaceIdSettingsSubscriptionRoute:
      ProtectedWWorkspaceIdSettingsSubscriptionRoute,
    ProtectedWWorkspaceIdSettingsTelegramSyncRoute:
      ProtectedWWorkspaceIdSettingsTelegramSyncRoute,
    ProtectedWWorkspaceIdToolsGroupParserRoute:
      ProtectedWWorkspaceIdToolsGroupParserRoute,
    ProtectedWWorkspaceIdToolsLookalikeAudienceRoute:
      ProtectedWWorkspaceIdToolsLookalikeAudienceRoute,
    ProtectedWWorkspaceIdToolsPhoneNumbersConverterRoute:
      ProtectedWWorkspaceIdToolsPhoneNumbersConverterRoute,
    ProtectedWWorkspaceIdWalletTopUpRoute:
      ProtectedWWorkspaceIdWalletTopUpRoute,
    ProtectedWWorkspaceIdContactsIndexRoute:
      ProtectedWWorkspaceIdContactsIndexRoute,
    ProtectedWWorkspaceIdOnboardingIndexRoute:
      ProtectedWWorkspaceIdOnboardingIndexRoute,
    ProtectedWWorkspaceIdOutreachIndexRoute:
      ProtectedWWorkspaceIdOutreachIndexRoute,
    ProtectedWWorkspaceIdSettingsIndexRoute:
      ProtectedWWorkspaceIdSettingsIndexRoute,
    ProtectedWWorkspaceIdContactsContactIdEditRoute:
      ProtectedWWorkspaceIdContactsContactIdEditRoute,
    ProtectedWWorkspaceIdOutreachTelegramAccountsAccountIdRoute:
      ProtectedWWorkspaceIdOutreachTelegramAccountsAccountIdRoute,
    ProtectedWWorkspaceIdOutreachTelegramAccountsBuyRoute:
      ProtectedWWorkspaceIdOutreachTelegramAccountsBuyRoute,
    ProtectedWWorkspaceIdOutreachTelegramAccountsNewRoute:
      ProtectedWWorkspaceIdOutreachTelegramAccountsNewRoute,
    ProtectedWWorkspaceIdSettingsApiKeysKeyIdRoute:
      ProtectedWWorkspaceIdSettingsApiKeysKeyIdRoute,
    ProtectedWWorkspaceIdSettingsOrganizationOrganizationIdRoute:
      ProtectedWWorkspaceIdSettingsOrganizationOrganizationIdRoute,
    ProtectedWWorkspaceIdSettingsWorkspaceInviteRoute:
      ProtectedWWorkspaceIdSettingsWorkspaceInviteRoute,
    ProtectedWWorkspaceIdSettingsWorkspaceNewRoute:
      ProtectedWWorkspaceIdSettingsWorkspaceNewRoute,
    ProtectedWWorkspaceIdContactsContactIdIndexRoute:
      ProtectedWWorkspaceIdContactsContactIdIndexRoute,
    ProtectedWWorkspaceIdOutreachTelegramAccountsIndexRoute:
      ProtectedWWorkspaceIdOutreachTelegramAccountsIndexRoute,
    ProtectedWWorkspaceIdSettingsApiKeysIndexRoute:
      ProtectedWWorkspaceIdSettingsApiKeysIndexRoute,
    ProtectedWWorkspaceIdSettingsWorkspaceIndexRoute:
      ProtectedWWorkspaceIdSettingsWorkspaceIndexRoute,
    ProtectedWWorkspaceIdContactsContactIdActivitiesNewRoute:
      ProtectedWWorkspaceIdContactsContactIdActivitiesNewRoute,
    ProtectedWWorkspaceIdOutreachSequencesIdAccountsRoute:
      ProtectedWWorkspaceIdOutreachSequencesIdAccountsRoute,
    ProtectedWWorkspaceIdOutreachSequencesIdLeadsRoute:
      ProtectedWWorkspaceIdOutreachSequencesIdLeadsRoute,
    ProtectedWWorkspaceIdOutreachSequencesNewCrmRoute:
      ProtectedWWorkspaceIdOutreachSequencesNewCrmRoute,
    ProtectedWWorkspaceIdOutreachSequencesNewCsvRoute:
      ProtectedWWorkspaceIdOutreachSequencesNewCsvRoute,
    ProtectedWWorkspaceIdSettingsApiKeysWebhooksWebhookIdRoute:
      ProtectedWWorkspaceIdSettingsApiKeysWebhooksWebhookIdRoute,
    ProtectedWWorkspaceIdSettingsWorkspaceUserUserIdRoute:
      ProtectedWWorkspaceIdSettingsWorkspaceUserUserIdRoute,
    ProtectedWWorkspaceIdOutreachSequencesIdIndexRoute:
      ProtectedWWorkspaceIdOutreachSequencesIdIndexRoute,
    ProtectedWWorkspaceIdOutreachSequencesNewIndexRoute:
      ProtectedWWorkspaceIdOutreachSequencesNewIndexRoute,
    ProtectedWWorkspaceIdSettingsApiKeysWebhooksIndexRoute:
      ProtectedWWorkspaceIdSettingsApiKeysWebhooksIndexRoute,
    ProtectedWWorkspaceIdSettingsPropertiesObjectTypeIndexRoute:
      ProtectedWWorkspaceIdSettingsPropertiesObjectTypeIndexRoute,
    ProtectedWWorkspaceIdContactsContactIdActivitiesActivityIdEditRoute:
      ProtectedWWorkspaceIdContactsContactIdActivitiesActivityIdEditRoute,
    ProtectedWWorkspaceIdOutreachSequencesIdContactSettingsOwnersRoute:
      ProtectedWWorkspaceIdOutreachSequencesIdContactSettingsOwnersRoute,
    ProtectedWWorkspaceIdSettingsMembersAcceptInviteWIdInviteCodeRoute:
      ProtectedWWorkspaceIdSettingsMembersAcceptInviteWIdInviteCodeRoute,
    ProtectedWWorkspaceIdSettingsPropertiesObjectTypeKeyEditRoute:
      ProtectedWWorkspaceIdSettingsPropertiesObjectTypeKeyEditRoute,
    ProtectedWWorkspaceIdSettingsPropertiesObjectTypeNewTypeRoute:
      ProtectedWWorkspaceIdSettingsPropertiesObjectTypeNewTypeRoute,
    ProtectedWWorkspaceIdSettingsWorkspaceAcceptInviteWIdInviteCodeRoute:
      ProtectedWWorkspaceIdSettingsWorkspaceAcceptInviteWIdInviteCodeRoute,
    ProtectedWWorkspaceIdOutreachSequencesIdContactSettingsIndexRoute:
      ProtectedWWorkspaceIdOutreachSequencesIdContactSettingsIndexRoute,
  }

const ProtectedWWorkspaceIdRouteRouteWithChildren =
  ProtectedWWorkspaceIdRouteRoute._addFileChildren(
    ProtectedWWorkspaceIdRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedWWorkspaceIdRouteRoute: typeof ProtectedWWorkspaceIdRouteRouteWithChildren
  ProtectedMiniAppSplatRoute: typeof ProtectedMiniAppSplatRoute
  ProtectedAcceptInviteWorkspaceIdInviteCodeRoute: typeof ProtectedAcceptInviteWorkspaceIdInviteCodeRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedWWorkspaceIdRouteRoute: ProtectedWWorkspaceIdRouteRouteWithChildren,
  ProtectedMiniAppSplatRoute: ProtectedMiniAppSplatRoute,
  ProtectedAcceptInviteWorkspaceIdInviteCodeRoute:
    ProtectedAcceptInviteWorkspaceIdInviteCodeRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  LocalRedirectRouteRoute: LocalRedirectRouteRoute,
  CelloRoute: CelloRoute,
  CustomTokenAuthRoute: CustomTokenAuthRoute,
  GoogleCalendarCallbackRoute: GoogleCalendarCallbackRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
